AGREEMENT_TEXT = """
PUBLISHER AGREEMENT

This Agreement (the "Agreement"), is entered into and made effective as of the Effective Date, by and between:

SURVTIT MARKET RESEARCH SURVEY LLP, a Limited Liability Partnership duly incorporated under the laws of India (LLPIN: ACB-8160, PAN: AFAFS9301P, TAN: MRTS28234D), with its address at 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, Uttar Pradesh, India ("Company"), of the one part;

AND

The Publisher ("Publisher"), of the other part;

(Hereinafter collectively referred to as "the Parties" and individually as a "Party").

WHEREAS: Company provides, among other services, a service that enables web users to obtain virtual currency, which may be used for various websites, online games, social applications, social networks, and other similar online applications by either earning (by completing offers) or purchasing such virtual currency; and

WHEREAS, the Publisher desires to collaborate with the Company, on a non-exclusive basis, for the purpose of promoting and providing the Service as defined hereunder, in accordance with the terms and conditions set forth below, and the Company desires to accept the Publisher's collaboration.

NOW, THEREFORE, in consideration of the mutual agreements contained herein, and upon the terms and subject to the conditions hereinafter set forth, the Parties do hereby agree as follows:

1. DEFINITIONS
"Publisher Application" Means a website and/or application and/or other virtual space provided, owned, or controlled by Publisher.
"User" Means any individual engaging with the Publisher Application.
"User Data" Means any data provided by Users to either Party (or its affiliates) in connection with an Offer.
"PII" Means any information relating to an identified or identifiable specific individual.
"Profile Data" Means demographic and other similar data provided by a User to either Party (excluding any data considered PII).
"Company Content" Means text, information, branding, and/or other material provided by Company to Publisher for use in connection with the Service.
"Company Client" Means any individual or entity providing an Offer.
"Service" Means Company's service, which enables a User to complete an Offer.
"Offer" Means an offer from a Company Client that is made available to Users on or through the Service.
"VC" Means the virtual currency Publisher provides to Users, including, but not limited to, awards made in connection with a Transaction.
"Action" Means any User action linked to an Offer, including, but not limited to, any registration, form submission, response, or other action specified by the Company Client.
"Transaction" Means the occurrence of a User completing an Offer and taking all relevant actions and/or meeting all requirements established by the Company Client with respect to said Offer.
"Exchange Rate" Means a representation, set, if not agreed otherwise by both Parties, by the Company Client, of the amount of VC that can be obtained by a User for each U.S. Dollar payable to Publisher.
"Gross Monthly Revenue" Means the total revenue generated by Transactions during a calendar month, based solely on data recorded by the Company.
"Payout" Means the Gross Monthly Revenue paid by the Company to the Publisher, in accordance with the terms of this Agreement, derived from the accumulated number of Transactions and according to the Exchange Rate.
"Fraudulent Activity" Means any activity, including, but not limited to, the use of any spyware, proxy servers, program, robot, redirects, or any automated and/or artificial and/or fraudulent methods designed to appear like an individual, real-life person performing a payout-generating event.
"Dashboard" Means an online element of the Service that enables managing and monitoring aspects of the Service, including, but not limited to, real-time daily aggregating and reporting of transactions and support tools.

2. IMPLEMENTATION
2.1 Company shall provide Publisher with the Service, including Company Content, to enable Publisher to make Offers available to Users via the Publisher Application.
2.2 During the term of this Agreement and for this Agreement only, Company will integrate and optimise the platform used to publish Offers on the Publisher Application.
2.3 The Publisher may log in to the Dashboard to monitor information relating to Transactions.
2.4 User and/or Publisher support – Company will respond to User's inquiries relating to Transactions made via the Service and provide technical support to Publisher, according to its policies and regulations.
2.5 Territory – Service included in this Agreement is not geographically restricted.

3. REPRESENTATION AND WARRANTIES
Each party represents, warrants, and covenants that:
3.1 It has full power to execute and deliver this Agreement and to perform its obligations hereunder, and all necessary corporate and other actions have been taken to authorise the execution and delivery of this Agreement and the performance of such obligations.
3.2 The execution of this Agreement shall not infringe on any third party's intellectual property rights.
3.3 It will ensure that any confidential information, trade secrets or any intellectual property rights of any other person or entity are not used without their permission.
3.4 It shall comply with all applicable international, state, and local laws and government rules and regulations and shall use only legitimate and ethical business practices in connection with this Agreement.
3.5 It shall maintain, display to Users, and abide by a privacy policy that complies with all applicable laws and regulations with respect to the collection, use, and transfer of User Data, including but not limited to any restrictions and/or regulations regarding PII and/or Profile Data. The Party's failure to maintain and comply with said policy shall constitute a material breach of this Agreement.
3.6 It will ensure that any of its systems and/or access it may have to systems of the other Party (including affiliates) will not impair the integrity and availability of such systems and will not deliver any (i) viruses, worms, time bombs, trojan horses or other harmful, malicious, or destructive code; and (ii) software disabling devices, time-out devices, counter devices, and devices intended to collect data regarding usage or related statistics without the prior written authorization of the other Party.
3.7 It will not promote or contain content that is illegal, harmful, threatening, defamatory, obscene, sexually explicit, harassing, promotes violence and/or discrimination, and/or illegal activities of any kind.
3.8 It shall be responsible for its own compliance with any applicable data protection laws and regulations.
3.9 Offers and/or Publisher Application may include links to other websites or resources that either Party has no control over and is not responsible or liable for such third-party's content, products, advertising, or availability.

4. PAYOUT TERMS
4.1 Payout currency: Payouts shall be processed in USD.
4.2 Payout timeline: Payment will be made within thirty (30) days after the end of each calendar month, for Transactions occurring during such month. The Publisher will provide the Company with a valid invoice.
4.3 Payout methods: PayPal or Bank Transfer.
4.4 Taxation: The Publisher is solely responsible for assessing and remitting its own local taxes.
4.5 Minimum Payout: It is agreed that any monthly Payout that does not meet the minimum threshold of $50 USD will be carried over to the Payout of the following month.
4.6 Fraudulent Activity and Chargebacks - Company will have the right, in its full discretion, to deduct and/or chargeback Payouts resulting from Fraudulent Activity. Furthermore, the Company reserves the right to claw back or deduct funds from future Payouts for a period of ninety (90) days post-transaction if leads/actions are subsequently rejected by the Company Client.
4.7 Tax Clause: No Indian GST applies as this is an export of services to a publisher outside India. Publisher is solely responsible for any taxes in its own jurisdiction.
4.8 Except for the Payout, Publisher will not be entitled to other payments, reimbursements, royalties, or expenses unless otherwise agreed in writing by the Parties. The Payout constitutes the entire payment due to Publisher under this Agreement, and Publisher shall not be entitled to any payments (including any reimbursement) other than those contained herein or specifically agreed in writing by Company.

5. INDEMNIFICATION
Each Party (in this article, "Indemnifying Party") shall defend, indemnify, protect and hold harmless the Other Party (in this article, "Injured Party"), and each of their officers, employees and agents from and against any claims, losses, demands, attorneys' fees, expenses, costs, damages, judgments, liabilities, causes of action, obligations or suits resulting from:
5.1 Any actual or alleged breach of any representation, warranty or other provision of this agreement by the Indemnifying Party or its personnel.
5.2 Any actual or alleged infringement of any third party's Intellectual Property rights.
5.3 Any negligent act or omission or willful misconduct, dishonesty or fraud of the Indemnifying Party or its personnel.
The Indemnifying Party's obligation to indemnify the Injured Party shall only apply in case the Injured Party:
5.4 Has given the Indemnifying Party prompt written notice of any third-party claim.
5.5 Cooperates reasonably with the Indemnifying Party in connection with the defence and settlement of such claim.
5.6 Shall not settle any such third-party claim without the Indemnifying Party's prior written approval.

6. CONFIDENTIALITY
6.1 Mutual NDA - The Parties will enter into a "Mutual Non-Disclosure Agreement" (the "NDA"), which is incorporated herein as Exhibit A. During the term of this Agreement, any confidential information disclosed shall be governed under the terms of the NDA. The NDA and the Parties' obligations, accordingly, shall remain in effect with respect to the confidential information exchanged under this Agreement throughout the term of this Agreement and for a period of three (3) years thereafter.
6.2 Publicity - Neither Party will use the other Party's name, logo, or trademarks or issue public announcements or press releases, make any statements, or confirm or comment on any information, public or otherwise, concerning the other Party's business, or the existence or subject matter of this Agreement.

7. OWNERSHIP AND LICENSING
7.1 Company's Ownership - As between Company and Publisher, Company shall retain sole and exclusive ownership of all rights, title, and interest, in and to the Service (except for any of Publisher's content or Offers included therein), including, but not limited to all software, information, data, documents, know-how, methods, processes, hardware and other intellectual property rights that are provided or used by Company in connection with the Service, including all intellectual property rights related thereto.
7.2 Publisher's Ownership - As between Company and Publisher, Publisher shall retain sole and exclusive ownership of all rights, title, and interest, in and to the Publisher Application (except for any Offer and/or Company Content included therein), including, but not limited to all software, information, data, documents, know-how, methods, processes, hardware and other intellectual property rights related thereto.

8. LIABILITY
EXCEPT FOR BREACH OF ARTICLES 6-7, BREACH OF ARTICLES 7.1-7.2, BREACH OF ARTICLE 3.1, BREACH OF ARTICLES 3.2-3.7, AND THE PARTIES OBLIGATIONS UNDER ARTICLE 5, IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT, STATUTE, IMPLIED DUTIES OR OBLIGATIONS, OR OTHER LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF EITHER PARTY IS FOUND LIABLE FOR DAMAGES IN CONNECTION WITH THIS AGREEMENT, ITS TOTAL LIABILITY SHALL NOT EXCEED THE TOTAL PAYOUT ACTUALLY PAID UNDER THIS AGREEMENT.

9. TERM AND TERMINATION
9.1 The term of this Agreement will begin on the Effective Date and will remain in effect until terminated in accordance with this Agreement.
9.2 Termination for convenience - Either Party may terminate this Agreement for its convenience, without liability, at any time, upon thirty (30) days' written notice to the other Party.
9.3 Termination for cause - Each Party may terminate this Agreement due to a breach of the other Party, which was not cured within 30 days from receipt of notice thereto (to the extent such breach can be cured), without derogating its right to seek and obtain all remedies available to it in law or in equity.
9.4 Either Party may terminate this Agreement immediately and without notice, upon discovery of Fraudulent Activity.
9.5 In addition, either party may terminate this Agreement if the other party seeks protection under any bankruptcy, receivership, trust deed, creditors' arrangement, personal insolvency, or comparable proceeding.
9.6 Payment Upon Termination – In the event of termination for whatever reason, Company will pay Publisher the undisputed Payout due and payable to Publisher through the date of termination, regardless of whether such Payout reaches the Minimum Payout.

10. UPON TERMINATION OR EXPIRATION
Upon termination or expiration of this Agreement, whichever occurs first, each Party shall promptly return or destroy and erase from all its systems all originals and copies of all documents, materials, and other expressions in any form or medium of Confidential Information and materials provided by the other Party.

11. NON-EXCLUSIVE RELATIONSHIP
Each party expressly reserves the right to contract with other third parties to provide or acquire Services similar or identical to Services provided under this Agreement.

12. MUTUAL NON-SOLICITATION
During the term of the Agreement and for a period of twelve (12) months thereafter, neither Party will, either directly or indirectly (whether through its respective employees, independent contractors, consultants, or otherwise), employ or engage, or solicit for employment or engagement, any employee, independent contractor, consultant, agent, or representative of the other Party.

13. ASSIGNABILITY
Publisher may not assign or transfer this Agreement or any rights or obligations hereunder without the prior written consent of Company. Company shall not assign or transfer this Agreement or any rights or obligations hereunder without providing a prior written notice to the Publisher.

14. APPLICABLE LAW AND JURISDICTION
It is hereby agreed between the parties that the laws of the State of India shall apply to this Agreement and that the sole and exclusive place of jurisdiction in any matter arising out of or in connection with this Agreement shall be the competent courts at Saharanpur, Uttar Pradesh, India.

15. ENTIRETY OF THE AGREEMENT
This Agreement constitutes the full and complete statement of the agreement of the Parties with respect to the subject matter hereof and supersedes all prior agreements, representations, warranties, understandings, relationships, whether written or oral, between the Parties, with respect to the subject matter hereof.

16. AMENDMENTS
Changes or modifications to this Agreement may not be made orally, but only by a written amendment signed by both Parties.

17. GENERAL
17.1 This Agreement shall not be construed to create a partnership, joint venture, or the relationship of principal and agent, employer, or employee between the parties.
17.2 The waiver of any right herein contained by either Party shall not be construed as a waiver of the same right at a future date or as a waiver of any other right herein contained.
17.3 The article headings used in this Agreement are for convenience of reference only and will not affect the interpretation hereof. Unless the context otherwise requires, as used in this Agreement, all terms used in the singular will be deemed to refer to the plural as well, and vice versa. As used in this Agreement, the word "including" is not a word of limitation.
17.4 If any provision of this Agreement shall be determined to be illegal or unenforceable, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement shall otherwise remain in full force and effect and enforceable.
17.5 The parties may execute this Agreement in counterparts. Each counterpart shall constitute an original document, and all counterparts shall constitute the same agreement.

18. NOTICES
All notices or other communications that either Party must make to the other shall be made in writing and shall be understood to have been done correctly if delivered by hand, mail, email, or facsimile and addressed to the Party at the address contained in this Agreement or such other address as shall have been notified to the other for this Agreement. Any notice given by mail shall be deemed given upon the expiration of five (5) days after mailing and in proving such mailing it shall be sufficient to show that the envelope containing the notice was properly addressed and posted as an airmail or first class pre-paid letter. Any notice given by facsimile shall be deemed to have been given at midnight (in the country of dispatch) on the date on which it was dispatched. E-mail correspondence shall constitute a notice under this Agreement, provided that the receipt of such e-mail by the recipient can be reasonably proved by the sender.

Company: SURVTIT MARKET RESEARCH SURVEY LLP, 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, UP, India. Email: shivam@survtit.com

EXHIBIT A — MUTUAL NON-DISCLOSURE AGREEMENT

This Mutual Non-Disclosure Agreement (this "Agreement") is entered into and made effective as of the Effective Date, by and between:

SURVTIT MARKET RESEARCH SURVEY LLP, a Limited Liability Partnership duly incorporated under the laws of India (LLPIN: ACB-8160, PAN: AFAFS9301P, TAN: MRTS28234D), with its address at 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, Uttar Pradesh, India("Company"), of the one part;

— AND —

The Publisher ("Publisher"), of the other party;

(Hereinafter collectively referred to as "the Parties" and individually as a "Party").

WHEREAS: Company provides, among other services, a service that enables web users to obtain virtual currency, which may be used for various websites, online games, social applications, social networks, and other similar online applications by either earning (by completing offers) or purchasing such virtual currency; and

WHEREAS, the Publisher desires to collaborate with the Company, on a non-exclusive basis, for the purpose of promoting and providing the Service as defined under the main Publisher Agreement, in accordance with the terms and conditions set forth below, and the Company desires to accept the Publisher's collaboration.

NOW, THEREFORE, in consideration of the mutual agreements contained herein, and upon the terms and subject to the conditions hereinafter set forth, the Parties do hereby agree as follows:

1. CONFIDENTIAL INFORMATION
For this Agreement "Confidential Information" means all information, disclosed by one party (the "Disclosing Party") to the other party (the "Receiving Party"), whether in oral or in written form, including but not limited to documentation, scientific, designs, software, prototypes, product descriptions, technical or business information, ideas, discoveries, inventions, specifications, formulas, processes, programs, plans, drawings, models, network configuration and rights-of-way, requirements, standards, financial and non-financial data, marketing, trade secrets, know-how, customer lists, prices, as well as all intellectual and industrial property rights contained therein and/or in relation thereto; provided however, that Confidential Information shall not include information which:
1.1 is or becomes lawfully in the public domain other than through a breach of any non-disclosure agreement or any confidentiality obligation,
1.2 was known to the Receiving Party before the disclosure, as evidenced by its business records,
1.3 was independently developed by or for the Receiving Party without reference to or use of Confidential Information received from the Disclosing Party,
1.4 was lawfully obtained by the Receiving Party from a third party without violation of a confidentiality obligation,
1.5 The Disclosing Party agrees in writing that it may be disclosed by the Receiving Party.
The Receiving Party shall have the burden of proving that any of the above exceptions apply by means of documentary evidence available at the time the Receiving Party claims the exception first became applicable.

2. NONDISCLOSURE OBLIGATIONS
2.1 CONFIDENTIAL INFORMATION USE
Confidential Information of a Disclosing Party shall be used by the Receiving Party solely for the purpose of the agreement to which this non-disclosure agreement is annexed and shall not be used for any other purpose. Each party shall hold the other party's Confidential Information in strictest confidence and shall not disclose the other party's Confidential Information without the prior written consent of such other party. Each party may disclose the other party's Confidential Information to such party's employees on a need-to-know basis. Each party agrees to take all reasonable precautions to protect the Confidential Information of the other party from falling into the public domain or the possession of persons other than those persons authorized to have any such Confidential Information according to this Agreement, which precautions shall include the highest degree of care that such party utilizes to protect its own information of a similar nature, but in no event less than a reasonable degree of care.
2.2 REQUIRED DISCLOSURE
Nothing in this Agreement shall prohibit either party from disclosing Confidential Information of the other party if legally required to do so by judicial or governmental order or in a judicial or governmental proceeding ("Required Disclosure"), provided that the discloser then shall: 2.2.1 give the other party prompt notice of such Required Disclosure before disclosure; 2.2.2 cooperate with the other party if the other party elects to contest such disclosure or seek a protective order with respect thereto, and/or 2.2.3 in any event only disclose the exact Confidential Information, or portion thereof, specifically requested by the Required Disclosure.

3. OWNERSHIP
All Confidential Information of a Disclosing Party is and shall remain the property of the Disclosing Party. Nothing contained in this Agreement shall be construed as granting or conferring any rights by license or otherwise, either express, implied or by estoppel, to any Confidential Information of a Disclosing Party, or under any patent, copyright, trademark or trade secret of the Disclosing Party.

4. DISCLAIMER OF WARRANTIES
ALL CONFIDENTIAL INFORMATION FURNISHED UNDER THIS AGREEMENT IS PROVIDED BY THE DISCLOSING PARTY "AS IS". NEITHER PARTY MAKES ANY WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, PERFORMANCE, MERCHANTABILITY, FITNESS FOR USE, OR OTHER ATTRIBUTES OF ITS RESPECTIVE CONFIDENTIAL INFORMATION.

5. RETURN OF CONFIDENTIAL INFORMATION
Immediately upon (i) request by the Disclosing Party at any time, or (ii) the termination of this Agreement, the Receiving Party shall return to the Disclosing Party all copies or extracts of the Disclosing Party's Confidential Information, in any medium and upon the Disclosing Party's request to certify in writing by an authorized officer of the Receiving Party, the destruction of the same to the Disclosing Party, except for one archival copy that may be retained by the Receiving Party's legal counsel to monitor compliance with the terms of this agreement only.

6. ASSIGNMENT AND TRANSFER
Neither party may assign or transfer this Agreement or any of its rights hereunder or delegate any of its obligations hereunder (whether by merger, operation of law or in any other manner) without the prior written consent of the other party, which consent may be withheld at such party's sole discretion.

7. NON-LIMITATION OF RIGHTS
Nothing contained in this Agreement shall be construed: 7.1 to limit either party's right to independently develop or acquire products without the use or benefit of the other party's Confidential Information, 7.2 as obligating either party to purchase or provide products from or to the other party, 7.3 to require either party to disclose or receive Confidential Information of the other party.

8. INDEPENDENT CONTRACTORS
The parties are independent contractors. Nothing in this Agreement or in the activities contemplated by the parties hereunder shall be deemed to create an agency, partnership, employment or joint venture relationship between the parties.

9. NOTICES
Notices to Company: SURVTIT MARKET RESEARCH SURVEY LLP, 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, UP, India. Email: shivam@survtit.com
Notices to Publisher: The address and email provided in the main Publisher Agreement.

10. APPLICABLE LAW AND DISPUTE RESOLUTION
This Agreement and any matters that are connected directly and/or indirectly to it, shall be governed, construed and interpreted according to the laws of India. Any dispute shall be settled exclusively in the venue of the competent court of Saharanpur, Uttar Pradesh, India.

11. EQUITABLE RELIEF
Each party acknowledges and agrees that due to the unique nature of the Disclosing Party's Confidential Information, there can be no adequate remedy at law for any breach of its obligations hereunder, that any such breach may allow the Receiving Party or third parties to unfairly compete with the Disclosing Party resulting in irreparable harm to the Disclosing Party and, therefore, that upon any such breach or any threat thereof, the Disclosing Party shall be entitled to appropriate equitable relief in addition to whatever remedies it might have at law.

12. TERMINATION AND SURVIVAL
This Agreement shall terminate upon termination of the main Publisher Agreement to which this non-disclosure agreement is annexed. Nevertheless, the obligations of the Receiving Party with respect to Confidential Information received prior to termination, will survive for a period of three (3) years following termination or expiration of this Agreement.

13. SEVERABILITY
If any provision of this Agreement shall be held by a court of competent jurisdiction to be illegal, invalid or unenforceable, the remaining provisions shall remain in full force and effect.

14. ENTIRE AGREEMENT
This Agreement shall not be modified except by a written agreement signed by both parties. No delay, failure or waiver of either party's exercise or partial exercise of any right or remedy under this Agreement shall operate to limit, impair, preclude, cancel, waive or otherwise affect such right or remedy. No waiver of any provision of this Agreement shall constitute a waiver of any other provision(s) or of the same provision on another occasion.

15. COUNTERPARTS
This Agreement may be executed in counterparts, each of which shall be deemed an original but all of which together shall constitute one and the same instrument.
"""
