import { useState } from 'react';
import { motion } from 'framer-motion';
import { FileText, ChevronRight, Clock, CheckCircle2 } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { format } from 'date-fns';

const DEFINITIONS = [
  ["Publisher Application", "Means a website and/or application and/or other virtual space provided, owned, or controlled by Publisher."],
  ["User", "Means any individual engaging with the Publisher Application."],
  ["User Data", "Means any data provided by Users to either Party (or its affiliates) in connection with an Offer."],
  ["PII", "Means any information relating to an identified or identifiable specific individual."],
  ["Profile Data", "Means demographic and other similar data provided by a User to either Party (excluding any data considered PII)."],
  ["Company Content", "Means text, information, branding, and/or other material provided by Company to Publisher for use in connection with the Service."],
  ["Company Client", "Means any individual or entity providing an Offer."],
  ["Service", "Means Company's service, which enables a User to complete an Offer."],
  ["Offer", "Means an offer from a Company Client that is made available to Users on or through the Service."],
  ["VC", "Means the virtual currency Publisher provides to Users, including, but not limited to, awards made in connection with a Transaction."],
  ["Action", "Means any User action linked to an Offer, including, but not limited to, any registration, form submission, response, or other action specified by the Company Client."],
  ["Transaction", "Means the occurrence of a User completing an Offer and taking all relevant actions and/or meeting all requirements established by the Company Client with respect to said Offer."],
  ["Exchange Rate", "Means a representation, set, if not agreed otherwise by both Parties, by the Company Client, of the amount of VC that can be obtained by a User for each U.S. Dollar payable to Publisher."],
  ["Gross Monthly Revenue", "Means the total revenue generated by Transactions during a calendar month, based solely on data recorded by the Company."],
  ["Payout", "Means the Gross Monthly Revenue paid by the Company to the Publisher, in accordance with the terms of this Agreement, derived from the accumulated number of Transactions and according to the Exchange Rate."],
  ["Fraudulent Activity", "Means any activity, including, but not limited to, the use of any spyware, proxy servers, program, robot, redirects, or any automated and/or artificial and/or fraudulent methods designed to appear like an individual, real-life person performing a payout-generating event."],
  ["Dashboard", "Means an online element of the Service that enables managing and monitoring aspects of the Service, including, but not limited to, real-time daily aggregating and reporting of transactions and support tools."]
];

export const AgreementPage = () => {
  const [hasScrolledToBottom, setHasScrolledToBottom] = useState(false);
  const navigate = useNavigate();

  const userDataString = localStorage.getItem('onboarding_user_data');
  const userData = userDataString ? JSON.parse(userDataString) : {};
  const effectiveDate = format(new Date(), 'MMMM dd, yyyy');
  const publisherName = userData.fullName || userData.firstName + ' ' + userData.lastName || '[PUBLISHER NAME]';
  const publisherAddress = userData.fullAddress || (userData.streetAddress ? `${userData.streetAddress}, ${userData.city}, ${userData.stateProvince}, ${userData.country}` : '[PUBLISHER ADDRESS]');
  const publisherEmail = userData.email || '[PUBLISHER EMAIL]';

  const handleScroll = (e: React.UIEvent<HTMLDivElement>) => {
    const { scrollTop, scrollHeight, clientHeight } = e.currentTarget;
    if (scrollHeight - scrollTop <= clientHeight + 50) {
      setHasScrolledToBottom(true);
    }
  };

  return (
    <div className="min-h-screen bg-slate-50 py-12 px-4">
      <div className="max-w-5xl mx-auto">
        <div className="bg-white rounded-3xl shadow-2xl overflow-hidden border border-slate-100 flex flex-col h-[85vh]">
          {/* Header */}
          <div className="bg-slate-900 px-8 py-6 flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="w-12 h-12 bg-blue-600 rounded-xl flex items-center justify-center text-white shadow-lg shadow-blue-500/20">
                <FileText size={24} />
              </div>
              <div>
                <h1 className="text-xl font-bold text-white leading-none">Agreement Review</h1>
                <p className="text-slate-400 text-sm mt-1 flex items-center gap-2">
                  <Clock size={14} /> Please review the full document to proceed
                </p>
              </div>
            </div>
            {hasScrolledToBottom && (
              <motion.div
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                className="bg-green-500/10 text-green-400 px-4 py-2 rounded-full text-xs font-bold flex items-center gap-2 border border-green-500/20"
              >
                <CheckCircle2 size={14} /> Ready to Sign
              </motion.div>
            )}
          </div>

          {/* Document Content */}
          <div
            onScroll={handleScroll}
            className="flex-1 overflow-y-auto p-12 bg-slate-50/30"
          >
            <div className="max-w-4xl mx-auto bg-white shadow-sm border border-slate-200 rounded-2xl p-16 font-serif text-slate-800 leading-relaxed space-y-8 text-justify text-[13px]">
              <div className="text-center space-y-2 mb-12">
                <h1 className="text-2xl font-bold text-slate-900 uppercase underline">PUBLISHER AGREEMENT</h1>
              </div>

              <div className="space-y-4">
                <p>This Agreement (the "Agreement"), is entered into and made effective as of <strong>{effectiveDate}</strong> (the "Effective Date"), by and between:</p>
                <p className="pl-6">
                  <strong>SURVTIT MARKET RESEARCH SURVEY LLP</strong>, a Limited Liability Partnership duly incorporated under the laws of India (LLPIN: ACB-8160, PAN: AFAFS9301P, TAN: MRTS28234D), with its address at 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, Uttar Pradesh, India (<strong>"Company"</strong>), of the one part;
                </p>
                <p className="font-bold text-center italic">AND</p>
                <p className="pl-6">
                  <strong>{publisherName}</strong>, an individual residing at <strong>{publisherAddress}</strong> (hereinafter referred to as the <strong>"Publisher"</strong>), of the other part;
                </p>
                <p>(Hereinafter collectively referred to as "the Parties" and individually as a "Party").</p>
              </div>

              <div className="space-y-4">
                <p><strong>WHEREAS:</strong> Company provides, among other services, a service that enables web users to obtain virtual currency, which may be used for various websites, online games, social applications, social networks, and other similar online applications by either earning (by completing offers) or purchasing such virtual currency; and</p>
                <p><strong>WHEREAS,</strong> the Publisher desires to collaborate with the Company, on a non-exclusive basis, for the purpose of promoting and providing the Service as defined hereunder, in accordance with the terms and conditions set forth below, and the Company desires to accept the Publisher's collaboration.</p>
                <p><strong>NOW, THEREFORE,</strong> in consideration of the mutual agreements contained herein, and upon the terms and subject to the conditions hereinafter set forth, the Parties do hereby agree as follows:</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">1. DEFINITIONS</h3>
                <table className="w-full border-collapse border border-slate-300 font-sans text-[11px]">
                  <thead>
                    <tr className="bg-slate-100">
                      <th className="border border-slate-300 p-2 text-left">Term</th>
                      <th className="border border-slate-300 p-2 text-left">Definition</th>
                    </tr>
                  </thead>
                  <tbody>
                    {DEFINITIONS.map(([t, d], i) => (
                      <tr key={i} className={i % 2 === 0 ? 'bg-white' : 'bg-slate-50'}>
                        <td className="border border-slate-300 p-2 font-bold">{t}</td>
                        <td className="border border-slate-300 p-2">{d}</td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">2. IMPLEMENTATION</h3>
                <p>2.1 Company shall provide Publisher with the Service, including Company Content, to enable Publisher to make Offers available to Users via the Publisher Application.</p>
                <p>2.2 During the term of this Agreement and for this Agreement only, Company will integrate and optimise the platform used to publish Offers on the Publisher Application.</p>
                <p>2.3 The Publisher may log in to the Dashboard to monitor information relating to Transactions.</p>
                <p>2.4 User and/or Publisher support – Company will respond to User's inquiries relating to Transactions made via the Service and provide technical support to Publisher, according to its policies and regulations.</p>
                <p>2.5 Territory – Service included in this Agreement is not geographically restricted.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">3. REPRESENTATION AND WARRANTIES</h3>
                <p>Each party represents, warrants, and covenants that:</p>
                <p>3.1 It has full power to execute and deliver this Agreement and to perform its obligations hereunder, and all necessary corporate and other actions have been taken to authorise the execution and delivery of this Agreement and the performance of such obligations.</p>
                <p>3.2 The execution of this Agreement shall not infringe on any third party's intellectual property rights.</p>
                <p>3.3 It will ensure that any confidential information, trade secrets or any intellectual property rights of any other person or entity are not used without their permission.</p>
                <p>3.4 It shall comply with all applicable international, state, and local laws and government rules and regulations and shall use only legitimate and ethical business practices in connection with this Agreement.</p>
                <p>3.5 It shall maintain, display to Users, and abide by a privacy policy that complies with all applicable laws and regulations with respect to the collection, use, and transfer of User Data, including but not limited to any restrictions and/or regulations regarding PII and/or Profile Data. The Party's failure to maintain and comply with said policy shall constitute a material breach of this Agreement.</p>
                <p>3.6 It will ensure that any of its systems and/or access it may have to systems of the other Party (including affiliates) will not impair the integrity and availability of such systems and will not deliver any (i) viruses, worms, time bombs, trojan horses or other harmful, malicious, or destructive code; and (ii) software disabling devices, time-out devices, counter devices, and devices intended to collect data regarding usage or related statistics without the prior written authorization of the other Party.</p>
                <p>3.7 It will not promote or contain content that is illegal, harmful, threatening, defamatory, obscene, sexually explicit, harassing, promotes violence and/or discrimination, and/or illegal activities of any kind.</p>
                <p>3.8 It shall be responsible for its own compliance with any applicable data protection laws and regulations.</p>
                <p>3.9 Offers and/or Publisher Application may include links to other websites or resources that either Party has no control over and is not responsible or liable for such third-party's content, products, advertising, or availability.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">4. PAYOUT TERMS</h3>
                <p>4.1 Payout currency: Payouts shall be processed in USD.</p>
                <p>4.2 Payout timeline: Payment will be made within thirty (30) days after the end of each calendar month, for Transactions occurring during such month. The Publisher will provide the Company with a valid invoice.</p>
                <p>4.3 Payout methods: PayPal or Bank Transfer.</p>
                <p>4.4 Taxation: The Publisher is solely responsible for assessing and remitting its own local taxes.</p>
                <p>4.5 Minimum Payout: It is agreed that any monthly Payout that does not meet the minimum threshold of $50 USD will be carried over to the Payout of the following month.</p>
                <p>4.6 Fraudulent Activity and Chargebacks - Company will have the right, in its full discretion, to deduct and/or chargeback Payouts resulting from Fraudulent Activity. Furthermore, the Company reserves the right to claw back or deduct funds from future Payouts for a period of ninety (90) days post-transaction if leads/actions are subsequently rejected by the Company Client.</p>
                <p>4.7 Tax Clause: No Indian GST applies as this is an export of services to a publisher outside India. Publisher is solely responsible for any taxes in its own jurisdiction.</p>
                <p>4.8 Except for the Payout, Publisher will not be entitled to other payments, reimbursements, royalties, or expenses unless otherwise agreed in writing by the Parties. The Payout constitutes the entire payment due to Publisher under this Agreement, and Publisher shall not be entitled to any payments (including any reimbursement) other than those contained herein or specifically agreed in writing by Company.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">5. INDEMNIFICATION</h3>
                <p>5.1 Any actual or alleged breach of any representation, warranty or other provision of this agreement by the Indemnifying Party or its personnel.</p>
                <p>5.2 Any actual or alleged infringement of any third party's Intellectual Property rights.</p>
                <p>5.3 Any negligent act or omission or willful misconduct, dishonesty or fraud of the Indemnifying Party or its personnel.</p>
                <p>5.4 Has given the Indemnifying Party prompt written notice of any third-party claim. 5.5 Cooperates reasonably with the Indemnifying Party in connection with the defence and settlement of such claim. 5.6 Shall not settle any such third-party claim without the Indemnifying Party's prior written approval.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">6. CONFIDENTIALITY</h3>
                <p>6.1 Mutual NDA - The Parties will enter into a "Mutual Non-Disclosure Agreement" (the "NDA"), which is incorporated herein as Exhibit A. During the term of this Agreement, any confidential information disclosed shall be governed under the terms of the NDA. The NDA and the Parties' obligations, accordingly, shall remain in effect with respect to the confidential information exchanged under this Agreement throughout the term of this Agreement and for a period of three (3) years thereafter.</p>
                <p>6.2 Publicity - Neither Party will use the other Party's name, logo, or trademarks or issue public announcements or press releases, make any statements, or confirm or comment on any information, public or otherwise, concerning the other Party's business, or the existence or subject matter of this Agreement.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">7. OWNERSHIP AND LICENSING</h3>
                <p>7.1 Company's Ownership - As between Company and Publisher, Company shall retain sole and exclusive ownership of all rights, title, and interest, in and to the Service (except for any of Publisher's content or Offers included therein), including, but not limited to all software, information, data, documents, know-how, methods, processes, hardware and other intellectual property rights that are provided or used by Company in connection with the Service, including all intellectual property rights related thereto.</p>
                <p>7.2 Publisher's Ownership - As between Company and Publisher, Publisher shall retain sole and exclusive ownership of all rights, title, and interest, in and to the Publisher Application (except for any Offer and/or Company Content included therein), including, but not limited to all software, information, data, documents, know-how, methods, processes, hardware and other intellectual property rights related thereto.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">8. LIABILITY</h3>
                <p>EXCEPT FOR BREACH OF ARTICLES 6-7, BREACH OF ARTICLES 7.1-7.2, BREACH OF ARTICLE 3.1, BREACH OF ARTICLES 3.2-3.7, AND THE PARTIES OBLIGATIONS UNDER ARTICLE 5, IN NO EVENT WILL EITHER PARTY BE LIABLE FOR ANY SPECIAL, INDIRECT, INCIDENTAL, OR CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, WHETHER SUCH DAMAGES ARE BASED ON CONTRACT, TORT, STATUTE, IMPLIED DUTIES OR OBLIGATIONS, OR OTHER LEGAL THEORY, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. IF EITHER PARTY IS FOUND LIABLE FOR DAMAGES IN CONNECTION WITH THIS AGREEMENT, ITS TOTAL LIABILITY SHALL NOT EXCEED THE TOTAL PAYOUT ACTUALLY PAID UNDER THIS AGREEMENT.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">9. TERM AND TERMINATION</h3>
                <p>9.1 The term of this Agreement will begin on the Effective Date and will remain in effect until terminated in accordance with this Agreement.</p>
                <p>9.2 Termination for convenience - Either Party may terminate this Agreement for its convenience, without liability, at any time, upon thirty (30) days' written notice to the other Party.</p>
                <p>9.3 Termination for cause - Each Party may terminate this Agreement due to a breach of the other Party, which was not cured within 30 days from receipt of notice thereto (to the extent such breach can be cured), without derogating its right to seek and obtain all remedies available to it in law or in equity.</p>
                <p>9.4 Either Party may terminate this Agreement immediately and without notice, upon discovery of Fraudulent Activity.</p>
                <p>9.5 In addition, either party may terminate this Agreement if the other party seeks protection under any bankruptcy, receivership, trust deed, creditors' arrangement, personal insolvency, or comparable proceeding.</p>
                <p>9.6 Payment Upon Termination – In the event of termination for whatever reason, Company will pay Publisher the undisputed Payout due and payable to Publisher through the date of termination, regardless of whether such Payout reaches the Minimum Payout.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">10. UPON TERMINATION OR EXPIRATION</h3>
                <p>Upon termination or expiration of this Agreement, whichever occurs first, each Party shall promptly return or destroy and erase from all its systems all originals and copies of all documents, materials, and other expressions in any form or medium of Confidential Information and materials provided by the other Party.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">11. NON-EXCLUSIVE RELATIONSHIP</h3>
                <p>Each party expressly reserves the right to contract with other third parties to provide or acquire Services similar or identical to Services provided under this Agreement.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">12. MUTUAL NON-SOLICITATION</h3>
                <p>During the term of the Agreement and for a period of twelve (12) months thereafter, neither Party will, either directly or indirectly (whether through its respective employees, independent contractors, consultants, or otherwise), employ or engage, or solicit for employment or engagement, any employee, independent contractor, consultant, agent, or representative of the other Party.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">13. ASSIGNABILITY</h3>
                <p>Publisher may not assign or transfer this Agreement or any rights or obligations hereunder without the prior written consent of Company. Company shall not assign or transfer this Agreement or any rights or obligations hereunder without providing a prior written notice to the Publisher.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">14. APPLICABLE LAW AND JURISDICTION</h3>
                <p>It is hereby agreed between the parties that the laws of the State of India shall apply to this Agreement and that the sole and exclusive place of jurisdiction in any matter arising out of or in connection with this Agreement shall be the competent courts at Saharanpur, Uttar Pradesh, India.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">15. ENTIRETY OF THE AGREEMENT</h3>
                <p>This Agreement constitutes the full and complete statement of the agreement of the Parties with respect to the subject matter hereof and supersedes all prior agreements, representations, warranties, understandings, relationships, whether written or oral, between the Parties, with respect to the subject matter hereof.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">16. AMENDMENTS</h3>
                <p>Changes or modifications to this Agreement may not be made orally, but only by a written amendment signed by both Parties.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">17. GENERAL</h3>
                <p>17.1 This Agreement shall not be construed to create a partnership, joint venture, or the relationship of principal and agent between the parties.</p>
                <p>17.2 The waiver of any right herein contained by either Party shall not be construed as a waiver of the same right at a future date.</p>
                <p>17.3 If any provision of this Agreement shall be determined to be illegal or unenforceable, that provision will be limited or eliminated to the minimum extent necessary.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">18. NOTICES</h3>
                <p>Notices to Company: 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, UP, India. Email: shivam@survtit.com</p>
                <p>Notices to Publisher: {publisherName}, {publisherAddress}. Email: {publisherEmail}</p>
              </div>

              <div className="pt-12 border-t-2 border-slate-900 space-y-12">
                <h3 className="text-xl font-bold uppercase">19. SIGNATURES</h3>
                <p className="italic text-slate-600">IN WITNESS WHEREOF, the Parties hereto, each by a duly authorised officer, have caused this Agreement to be executed on the last date written below.</p>
                <div className="grid grid-cols-2 gap-20">
                  <div className="space-y-4">
                    <p className="font-bold text-slate-400 uppercase text-xs">For Company</p>
                    <div className="h-24 border border-slate-100 bg-slate-50 flex items-center justify-center italic text-slate-400 text-center">Company Stamp Placeholder</div>
                    <div className="border-t border-slate-900 pt-2">
                      <p className="font-bold">Shivam Julka</p>
                      <p className="text-slate-500 text-xs">CMO / Co-founder</p>
                    </div>
                  </div>
                  <div className="space-y-4">
                    <p className="font-bold text-slate-400 uppercase text-xs">For Publisher</p>
                    <div className="h-24 border border-slate-100 bg-slate-50 flex items-center justify-center italic text-slate-400 text-center text-[10px]">Signature will appear here</div>
                    <div className="border-t border-slate-900 pt-2">
                      <p className="font-bold">{publisherName}</p>
                      <p className="text-slate-500 text-xs">Authorized Representative</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className="py-24 flex items-center justify-center gap-6">
                <div className="h-px bg-slate-200 flex-1"></div>
                <span className="text-slate-300 font-sans text-xs uppercase tracking-[0.5em] font-bold">Exhibit A Attached Below</span>
                <div className="h-px bg-slate-200 flex-1"></div>
              </div>

              <div className="text-center space-y-4 mb-12">
                <h2 className="text-xl font-bold text-slate-900 uppercase underline">MUTUAL NON-DISCLOSURE AGREEMENT</h2>
              </div>

              <div className="space-y-6">
                <p>This Mutual Non-Disclosure Agreement (this "Agreement") is entered into and made effective as of <strong>{effectiveDate}</strong> (the "Effective Date"), by and between:</p>
                <p className="pl-6 font-medium"><strong>SURVTIT MARKET RESEARCH SURVEY LLP</strong>, a Limited Liability Partnership duly incorporated under the laws of India (LLPIN: ACB-8160, PAN: AFAFS9301P, TAN: MRTS28234D), with its address at 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, Uttar Pradesh, India (<strong>"Company"</strong>);</p>
                <p className="font-bold text-center italic">— AND —</p>
                <p className="pl-6 font-medium"><strong>{publisherName}</strong>, an individual residing at <strong>{publisherAddress}</strong> (<strong>"Publisher"</strong>).</p>
              </div>

              <div className="space-y-4">
                <p><strong>WHEREAS:</strong> Company provides, among other services, a service that enables web users to obtain virtual currency, which may be used for various websites, online games, social applications, social networks, and other similar online applications by either earning (by completing offers) or purchasing such virtual currency; and</p>
                <p><strong>WHEREAS,</strong> the Publisher desires to collaborate with the Company, on a non-exclusive basis, for the purpose of promoting and providing the Service as defined under the main Publisher Agreement, in accordance with the terms and conditions set forth below, and the Company desires to accept the Publisher's collaboration.</p>
                <p><strong>NOW, THEREFORE,</strong> in consideration of the mutual agreements contained herein, and upon the terms and subject to the conditions hereinafter set forth, the Parties do hereby agree as follows:</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">1. CONFIDENTIAL INFORMATION</h3>
                <p>For this Agreement "Confidential Information" means all information, disclosed by one party (the "Disclosing Party") to the other party (the "Receiving Party"), whether in oral or in written form, including but not limited to documentation, scientific, designs, software, prototypes, product descriptions, technical or business information, ideas, discoveries, inventions, specifications, formulas, processes, programs, plans, drawings, models, network configuration and rights-of-way, requirements, standards, financial and non-financial data, marketing, trade secrets, know-how, customer lists, prices, as well as all intellectual and industrial property rights contained therein and/or in relation thereto.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">2. NONDISCLOSURE OBLIGATIONS</h3>
                <p>2.1 CONFIDENTIAL INFORMATION USE: Confidential Information of a Disclosing Party shall be used by the Receiving Party solely for the purpose of the agreement to which this non-disclosure agreement is annexed and shall not be used for any other purpose. Each party shall hold the other party's Confidential Information in strictest confidence and shall not disclose the other party's Confidential Information without the prior written consent of such other party.</p>
                <p>2.2 REQUIRED DISCLOSURE: Nothing in this Agreement shall prohibit either party from disclosing Confidential Information of the other party if legally required to do so by judicial or governmental order or in a judicial or governmental proceeding.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">3. OWNERSHIP</h3>
                <p>All Confidential Information of a Disclosing Party is and shall remain the property of the Disclosing Party. Nothing contained in this Agreement shall be construed as granting or conferring any rights by license or otherwise, either express, implied or by estoppel, to any Confidential Information of a Disclosing Party, or under any patent, copyright, trademark or trade secret of the Disclosing Party.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">4. DISCLAIMER OF WARRANTIES</h3>
                <p>ALL CONFIDENTIAL INFORMATION FURNISHED UNDER THIS AGREEMENT IS PROVIDED BY THE DISCLOSING PARTY "AS IS". NEITHER PARTY MAKES ANY WARRANTIES, EXPRESS OR IMPLIED, REGARDING THE ACCURACY, COMPLETENESS, PERFORMANCE, MERCHANTABILITY, FITNESS FOR USE, OR OTHER ATTRIBUTES OF ITS RESPECTIVE CONFIDENTIAL INFORMATION.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">5. RETURN OF CONFIDENTIAL INFORMATION</h3>
                <p>Immediately upon (i) request by the Disclosing Party at any time, or (ii) the termination of this Agreement, the Receiving Party shall return to the Disclosing Party all copies or extracts of the Disclosing Party's Confidential Information, in any medium.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">6. ASSIGNMENT AND TRANSFER</h3>
                <p>Neither party may assign or transfer this Agreement or any of its rights hereunder or delegate any of its obligations hereunder (whether by merger, operation of law or in any other manner) without the prior written consent of the other party.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">7. NON-LIMITATION OF RIGHTS</h3>
                <p>Nothing contained in this Agreement shall be construed: 7.1 to limit either party's right to independently develop or acquire products without the use or benefit of the other party's Confidential Information, 7.2 as obligating either party to purchase or provide products from or to the other party.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">8. INDEPENDENT CONTRACTORS</h3>
                <p>The parties are independent contractors. Nothing in this Agreement or in the activities contemplated by the parties hereunder shall be deemed to create an agency, partnership, employment or joint venture relationship between the parties.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">9. NOTICES</h3>
                <p>Notices to Company: SURVTIT MARKET RESEARCH SURVEY LLP, 11/1117/48, Mehndi Sarai, Jankipuram Police Station, Saharanpur-247001, UP, India. Email: shivam@survtit.com</p>
                <p>Notices to Publisher: {publisherName}, {publisherAddress}. Email: {publisherEmail}</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">10. APPLICABLE LAW AND DISPUTE RESOLUTION</h3>
                <p>This Agreement and any matters that are connected directly and/or indirectly to it, shall be governed, construed and interpreted according to the laws of India. Any dispute shall be settled exclusively in the venue of the competent court of Saharanpur, Uttar Pradesh, India.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">11. EQUITABLE RELIEF</h3>
                <p>Each party acknowledges and agrees that due to the unique nature of the Disclosing Party's Confidential Information, there can be no adequate remedy at law for any breach of its obligations hereunder.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">12. TERMINATION AND SURVIVAL</h3>
                <p>This Agreement shall terminate upon termination of the main Publisher Agreement to which this non-disclosure agreement is annexed. Nevertheless, the obligations of the Receiving Party with respect to Confidential Information received prior to termination, will survive for a period of three (3) years.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">13. SEVERABILITY</h3>
                <p>If any provision of this Agreement shall be held by a court of competent jurisdiction to be illegal, invalid or unenforceable, the remaining provisions shall remain in full force and effect.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">14. ENTIRE AGREEMENT</h3>
                <p>This Agreement shall not be modified except by a written agreement signed by both parties. No delay, failure or waiver of either party's exercise or partial exercise of any right or remedy under this Agreement shall operate to limit, impair, preclude, cancel, waive or otherwise affect such right or remedy.</p>
              </div>

              <div className="space-y-4">
                <h3 className="font-bold underline uppercase">15. COUNTERPARTS</h3>
                <p>This Agreement may be executed in counterparts, each of which shall be deemed an original but all of which together shall constitute one and the same instrument.</p>
              </div>

                <div className="pt-12 border-t-2 border-slate-900 space-y-12">
                  <h3 className="text-xl font-bold uppercase">16. SIGNATURES</h3>
                  <p className="italic text-slate-600">IN WITNESS WHEREOF, the Parties hereto have caused this NDA Agreement to be executed on the last date written below.</p>
                  <div className="grid grid-cols-2 gap-20">
                    <div className="space-y-4">
                      <p className="font-bold text-slate-400 uppercase text-xs">For Company</p>
                      <div className="h-24 border border-slate-100 bg-slate-50 flex items-center justify-center italic text-slate-400">Company Stamp Placeholder</div>
                      <div className="border-t border-slate-900 pt-2">
                        <p className="font-bold">Shivam Julka</p>
                        <p className="text-slate-500 text-xs">CMO / Co-founder</p>
                      </div>
                    </div>
                    <div className="space-y-4">
                      <p className="font-bold text-slate-400 uppercase text-xs">For Publisher</p>
                      <div className="h-24 border border-slate-100 bg-slate-50 flex items-center justify-center italic text-slate-400">Signature will appear here</div>
                      <div className="border-t border-slate-900 pt-2">
                        <p className="font-bold">{publisherName}</p>
                        <p className="text-slate-500 text-xs">Authorized Representative</p>
                      </div>
                    </div>
                  </div>
                </div>

                <div className="h-12 flex items-center justify-center mt-20">
                  <div className="h-px bg-slate-200 w-full"></div>
                  <span className="px-4 text-slate-300 font-sans text-xs whitespace-nowrap">End of Document</span>
                  <div className="h-px bg-slate-200 w-full"></div>
                </div>
              </div>
            </div>

          {/* Footer Actions */}
          <div className="p-8 border-t border-slate-100 bg-white flex justify-between items-center">
            <div className="flex flex-col">
              <span className="text-sm font-bold text-slate-900">Review Required</span>
              <span className="text-xs text-slate-500">Scroll to the bottom to proceed</span>
            </div>
            <button
              disabled={!hasScrolledToBottom}
              onClick={() => navigate('/signature')}
              className={`flex items-center gap-2 px-10 py-4 rounded-xl font-bold transition-all shadow-xl ${hasScrolledToBottom
                  ? 'bg-blue-600 text-white hover:bg-blue-700 shadow-blue-200'
                  : 'bg-slate-100 text-slate-400 cursor-not-allowed shadow-none'
                }`}
            >
              Proceed to Digital Signature <ChevronRight size={20} />
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
